services:

  postgres:
    image: postgres:16
    container_name: order-postgres
    env_file:
      - ./application/.env.docker
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: order_user
    ports:
      - "5433:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order_user -d orders_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./application
    container_name: order-api
    env_file:
      - ./application/.env.docker
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  order-db-data: