{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order-api
  namespace: {{ .Release.Namespace }}
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: order-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
