name: CD

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "GHCR image tag to deploy"
        required: true
        type: string

jobs:
  deploy:
    name: Deploy with Helm
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Create Kubernetes cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: devops-cluster

      - name: Verify Kubernetes cluster
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Create application secrets
        run: |
          kubectl create secret generic postgres-secret \
            --from-literal=POSTGRES_DB=orders_db \
            --from-literal=POSTGRES_USER=order_user \
            --from-literal=POSTGRES_PASSWORD=order_password

          kubectl create secret generic order-api-secret \
            --from-literal=DATABASE_URL=postgresql://order_user:order_password@postgres:5432/orders_db

      - name: Helm lint
        run: |
          helm lint helm/order-api

      - name: Helm deploy
        run: |
          helm upgrade --install order-api helm/order-api \
            --set image.repository=ghcr.io/harshchetwani/order-api \
            --set image.tag=${{ inputs.image_tag }} \
            --set monitoring.serviceMonitor.enabled=false \
            --set monitoring.prometheusRule.enabled=false \
            --wait \
            --timeout 5m

      - name: Verify deployment
        run: |
          kubectl get pods
          kubectl get services
          kubectl get deployments
          kubectl get pvc

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/postgres --timeout=5m
          kubectl rollout status deployment/order-api --timeout=5m

      - name: Verify application
        run: |
          kubectl get pods -l app=order-api
          kubectl exec deployment/order-api -- \
            python -c "import urllib.request; print(urllib.request.urlopen('http://localhost:8000/health').read().decode())"
